// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_translate_version.test.ts.

/** The version of the `@ggdna/dna-translate` package. */
export const dnaTranslateVersion = '0.1.1';
